spring:
  application:
    name: barber-shop-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/barberShopDb_barber
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 5002
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"
